"use client";

import { useState } from "react";
import type { Bond, CashFlow } from "@/types/bond";
import { CashFlowPanel } from "@/components/CashFlowPanel";
import { MaturityPanel } from "@/components/MaturityPanel";
import { ReportPanel } from "@/components/ReportPanel";

type ZeroCouponPoint = { valuationDate: string; maturityMode: string; maturity: number; zeroCouponRate: number };
type Tab = "base" | "zeroCoupon" | "cashflows" | "analysis" | "market" | "maturities" | "report";

export function AnalystApp({ email, bonds, cashFlows, zeroCouponCurve }: { email: string; bonds: Bond[]; cashFlows: CashFlow[]; zeroCouponCurve: ZeroCouponPoint[] }) {
  const [tab, setTab] = useState<Tab>("base");
  const tabs: { id: Tab; label: string }[] = [{ id: "base", label: "Base de valeur" }, { id: "zeroCoupon", label: "Courbe zero-coupon" }, { id: "cashflows", label: "Cash-flows" }, { id: "analysis", label: "Analyse obligations" }, { id: "market", label: "Marche secondaire" }, { id: "maturities", label: "Echeances" }, { id: "report", label: "Rapport financier" }];
  return <div className="min-h-[calc(100vh-8rem)] bg-gray-50"><div className="border-b border-gray-200 bg-white px-6 py-6"><div className="mx-auto max-w-7xl"><h1 className="text-2xl font-bold text-gray-900">Espace Analyste Financier</h1><p className="text-sm text-gray-500">Connecte en tant que {email} — donnees importees du fichier Excel.</p></div></div><div className="mx-auto max-w-7xl px-6 py-8"><div className="mb-6 flex flex-wrap gap-2">{tabs.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`rounded-full border px-4 py-1.5 text-sm ${tab === item.id ? "border-[#f28c28] bg-[#f28c28] text-white" : "border-gray-300 bg-white text-gray-700"}`}>{item.label}</button>)}</div><div className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">{tab === "base" && <BaseValuePanel bonds={bonds} />}{tab === "zeroCoupon" && <ZeroCouponPanel points={zeroCouponCurve} />}{tab === "cashflows" && <CashFlowPanel cashFlows={cashFlows} />}{tab === "analysis" && <AnalysisPanel bonds={bonds} />}{tab === "market" && <MarketPanel bonds={bonds} />}{tab === "maturities" && <MaturityPanel bonds={bonds} />}{tab === "report" && <ReportPanel bonds={bonds} />}</div></div></div>;
}

function BaseValuePanel({ bonds }: { bonds: Bond[] }) { return <div><h2 className="text-lg font-semibold">Base _ Valeur</h2><p className="mb-4 text-sm text-gray-500">Colonnes de la feuille Excel « Base _ Valeur ».</p><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs text-gray-500"><tr><th className="px-2 py-2">Code_Valeur</th><th className="px-2">Nominal</th><th className="px-2">Taux</th><th className="px-2">Date_Emission</th><th className="px-2">Date_Jouissance</th><th className="px-2">Date_Echeance</th><th className="px-2">WG</th><th className="px-2">CT</th><th className="px-2">CFG</th><th className="px-2">Taux/Revisable</th><th className="px-2">Amortissable</th><th className="px-2">Periodicite</th><th className="px-2">Echeancier</th><th className="px-2">Commentaires</th></tr></thead><tbody>{bonds.map((bond) => <tr key={bond.id} className="border-t"><td className="px-2 py-2 font-mono">{bond.isin}</td><td className="px-2">{bond.nominal.toLocaleString("fr-FR")}</td><td className="px-2">{bond.couponRate.toFixed(3)}%</td><td className="px-2">{bond.issueDate}</td><td className="px-2">{bond.valueDate ?? "—"}</td><td className="px-2">{bond.maturityDate}</td><td className="px-2">{bond.wgRate ?? "—"}</td><td className="px-2">{bond.ctRate ?? "—"}</td><td className="px-2">{bond.cfgRate ?? "—"}</td><td className="px-2">{bond.isFloating ? "Oui" : "Non"}</td><td className="px-2">{bond.isAmortizing ? "Oui" : "Non"}</td><td className="px-2">{bond.frequency}</td><td className="px-2">{bond.schedule ?? "—"}</td><td className="px-2">{bond.comments ?? "—"}</td></tr>)}</tbody></table></div></div>; }
function ZeroCouponPanel({ points }: { points: ZeroCouponPoint[] }) { return <div><h2 className="text-lg font-semibold">Courbe ZC</h2><p className="mb-4 text-sm text-gray-500">Colonnes Unite, Maturite et Taux de la feuille Excel « Courbe ZC ».</p><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs text-gray-500"><tr><th className="px-3 py-2">Date de valorisation</th><th className="px-3">Unite</th><th className="px-3">Maturite</th><th className="px-3">Taux</th></tr></thead><tbody>{points.map((point) => <tr key={`${point.valuationDate}-${point.maturityMode}-${point.maturity}`} className="border-t"><td className="px-3 py-2">{point.valuationDate}</td><td className="px-3">{point.maturityMode}</td><td className="px-3">{point.maturity}</td><td className="px-3">{point.zeroCouponRate.toFixed(8)}%</td></tr>)}</tbody></table></div>; }
function AnalysisPanel({ bonds }: { bonds: Bond[] }) { const active = bonds.filter((bond) => bond.status === "active"); const nominal = active.reduce((total, bond) => total + bond.nominal, 0); const coupon = active.length ? active.reduce((total, bond) => total + bond.couponRate, 0) / active.length : 0; return <div><h2 className="text-lg font-semibold">Analyse obligations</h2><div className="mt-5 grid grid-cols-3 gap-4"><Metric label="Titres actifs" value={String(active.length)} /><Metric label="Nominal actif" value={nominal.toLocaleString("fr-FR")} /><Metric label="Taux facial moyen" value={`${coupon.toFixed(3)}%`} /></div></div>; }
function MarketPanel({ bonds }: { bonds: Bond[] }) { const quoted = bonds.filter((bond) => bond.price !== null); return <div><h2 className="text-lg font-semibold">Marche secondaire</h2><table className="mt-4 min-w-full text-sm"><thead className="text-left text-xs text-gray-500"><tr><th>Code_Valeur</th><th>Date_Echeance</th><th>Prix</th></tr></thead><tbody>{quoted.map((bond) => <tr key={bond.id} className="border-t"><td className="py-2">{bond.isin}</td><td>{bond.maturityDate}</td><td>{bond.price?.toFixed(3)}</td></tr>)}</tbody></table></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-gray-200 bg-gray-50 p-4"><p className="text-xs text-gray-500">{label}</p><p className="text-xl font-semibold">{value}</p></div>; }
